"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sampleMessages = void 0;
exports.sampleMessages = [];
if (DEVELOPMENT) {
    exports.sampleMessages.push({ name: 'Soubi', message: 'Me lo hubieras dicho al menos.', type: 4 /* MessageType.Party */ }, { name: 'Doggy', message: 'Mira un menor' }, { name: 'carry *br*', message: 'menos frama vai...nunca te falei isso' }, { name: 'Doggy', message: 'A uste le gustan menores' }, { name: 'Doggy', message: 'Pero no soy menor de edad' }, { name: 'springtrap girl(:3)', message: 'pelo menos desincalho' }, { name: 'Foxy (Menina)', message: 'que vida em a metade do povo sabe menos nois ;-;' }, { name: 'Mangle (br)', message: 'mais pelo menos meus pais ta aqui em casa', type: 4 /* MessageType.Party */ }, { name: 'Experiment-z30 (ESP)', message: 'Con una menos en la clase' }, { name: '🌙 Ň✞ĦŦΜΔŘ€ ŞΔŇŞ 🌙', message: 'aceita q doi menos' }, { name: '⭐✨柊|Lihan|柊✨⭐', message: 'quanta frescura no rabo mano, aceita que doi menos' }, { name: '🌙 Ň✞ĦŦΜΔŘ€ ŞΔŇŞ 🌙', message: 'aceita q doi menos' }, { name: '⭐✨柊|Lihan|柊✨⭐', message: 'quanta frescura no rabo mano, aceita que doi menos' }, { name: 'Ilenos Pijama', message: 'Muito menos participar' }, { name: 'luz(br)', message: 'pelo menos fan nao vai comer todos os lanches' }, { name: '=tord=', message: 'quien saque menos' }, { name: 'ladybug', message: 'mais ou menos .-.' }, { name: 'springtrap girl(:3)', message: 'pelo menos desincalho' }, { name: 'Foxy (Menina)', message: 'que vida em a metade do povo sabe menos nois ;-;' }, { name: 'Experiment-z30 (ESP)', message: 'Con una menos en la clase' }, { name: 'Ilenos Pijama', message: 'Muito menos participar' }, { name: 'Mangle (br)', message: 'mais pelo menos meus pais ta aqui em casa', type: 4 /* MessageType.Party */ }, { name: 'luz(br)', message: 'pelo menos fan nao vai comer todos os lanches' }, {
        message: '/help - show help\n/roll [[min-]max] - randomize a number\n/s - say\n/p - party chat\n/t - thinking baloon',
        name: '', type: 1 /* MessageType.System */,
    }, { name: 'Molley', message: 'Some admin message here', type: 2 /* MessageType.Admin */ }, { name: 'Dolleyert', message: 'Some moderator message here', type: 3 /* MessageType.Mod */ }, { name: '', message: 'The server will restart soon', type: 7 /* MessageType.Announcement */ }, { name: 'Molley', message: '🎲 rolled 5 of 100', type: 7 /* MessageType.Announcement */ }, { name: 'Molley', message: 'Some thinki👻n👻g 🍎 mes<b>aaa</b>sage', type: 5 /* MessageType.Thinking */ }, { name: 'Molley', message: 'Some party thinking message', type: 6 /* MessageType.PartyThinking */ }, { name: 'Molley', message: 'Some supporter 🙂 message 1', type: 9 /* MessageType.Supporter1 */ }, { name: 'Molley', message: 'Some supporter 🙂 message 2', type: 10 /* MessageType.Supporter2 */, id: 1 }, { name: 'Molley', message: 'Some supporter 🙂 message 3', type: 11 /* MessageType.Supporter3 */, id: 2 }, { name: 'Molley', message: 'Some whisper message', type: 13 /* MessageType.Whisper */, id: 2 }, { name: 'WWWWWWWWWWWWWWWWWWWW', message: 'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW' }, { name: 'WWWWWWWWWWWWWWWWWWWW', message: 'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW' }, { name: 'tord ⚧☿♁⚨⚩⚦⚢⚣⚤', message: 'quien saque menos ⚧☿♁⚨⚩⚦⚢⚣⚤' }, { name: 'more symbols', message: '♈♉♊♋♌♍♎♏♐♑♒♓⛎♈♉♊♋♌♍♎♏♐♑♒♓⛎♈♉♊♋♌♍♎♏♐♑♒♓⛎' });
}
//# sourceMappingURL=debugData.js.map