"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.expressions = void 0;
const expressionUtils_1 = require("./expressionUtils");
exports.expressions = [
    // invalid
    ['', undefined],
    ['a', undefined],
    ['123', undefined],
    [':::', undefined],
    ['XDK', undefined],
    ['fooXD', undefined],
    [':) hey', undefined],
    ['тот', undefined],
    // in text
    [' :) ', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['hi :)', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    // horizontal (right)
    [':-)', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    [':)', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['=)', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    [':]', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    [':>', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    [':}', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    [':3', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['rus :з', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['rus :э', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    [':(', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 1 /* Muzzle.Frown */]],
    [':[', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 1 /* Muzzle.Frown */]],
    [':C', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 1 /* Muzzle.Frown */]],
    [':c', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 1 /* Muzzle.Frown */]],
    ['rus :С', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 1 /* Muzzle.Frown */]],
    ['rus :с', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 1 /* Muzzle.Frown */]],
    [':<', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 1 /* Muzzle.Frown */]],
    [':{', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 1 /* Muzzle.Frown */]],
    [':I', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 3 /* Muzzle.Scrunch */]],
    [':t', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 3 /* Muzzle.Scrunch */]],
    [':T', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 3 /* Muzzle.Scrunch */]],
    ['rus :Т', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 3 /* Muzzle.Scrunch */]],
    ['rus :т', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 3 /* Muzzle.Scrunch */]],
    [':P', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 4 /* Muzzle.Blep */]],
    [':p', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 4 /* Muzzle.Blep */]],
    [':d', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 4 /* Muzzle.Blep */]],
    [':b', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 25 /* Muzzle.FlatBlep */]],
    ['rus :Р', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 4 /* Muzzle.Blep */]],
    ['rus :р', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 4 /* Muzzle.Blep */]],
    [':D', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 5 /* Muzzle.SmileOpen */]],
    [':DD', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 9 /* Muzzle.SmileOpen2 */]],
    [':DDD', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 14 /* Muzzle.SmileOpen3 */]],
    [':DDDDD', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 14 /* Muzzle.SmileOpen3 */]],
    [':O', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 12 /* Muzzle.ConcernedOpen2 */]],
    [':0', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 8 /* Muzzle.ConcernedOpen */]],
    [':o', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 24 /* Muzzle.Oh */]],
    [':|', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */]],
    [':l', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */]],
    [':i', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */]],
    [':v', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 8 /* Muzzle.ConcernedOpen */]],
    [':V', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 10 /* Muzzle.FrownOpen */]],
    [':u', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 11 /* Muzzle.NeutralOpen2 */]],
    [':n', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 11 /* Muzzle.NeutralOpen2 */]],
    [':U', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 15 /* Muzzle.NeutralOpen3 */]],
    [':*', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 13 /* Muzzle.Kiss */]],
    [':x', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 13 /* Muzzle.Kiss */]],
    [':X', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 13 /* Muzzle.Kiss */]],
    [':/', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 7 /* Muzzle.Concerned */]],
    [':\\', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 7 /* Muzzle.Concerned */]],
    [':S', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 7 /* Muzzle.Concerned */]],
    [':s', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 7 /* Muzzle.Concerned */]],
    [':?', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 7 /* Muzzle.Concerned */]],
    ['>:(', [19 /* Eye.Angry */, 19 /* Eye.Angry */, 1 /* Muzzle.Frown */]],
    ['>:<', [19 /* Eye.Angry */, 19 /* Eye.Angry */, 1 /* Muzzle.Frown */]],
    ['<:>', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 0 /* Muzzle.Smile */]],
    ['XD', [23 /* Eye.X */, 23 /* Eye.X */, 5 /* Muzzle.SmileOpen */]],
    ['xD', [23 /* Eye.X */, 23 /* Eye.X */, 5 /* Muzzle.SmileOpen */]],
    [':L', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 23 /* Muzzle.NeutralPant */]],
    [':Q', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 22 /* Muzzle.SmilePant */]],
    ['B)', [3 /* Eye.Neutral3 */, 3 /* Eye.Neutral3 */, 0 /* Muzzle.Smile */]],
    ['8)', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */, 6 /* Iris.Shocked */, 6 /* Iris.Shocked */]],
    ['>8)', [19 /* Eye.Angry */, 19 /* Eye.Angry */, 0 /* Muzzle.Smile */, 6 /* Iris.Shocked */, 6 /* Iris.Shocked */]],
    ['<:)', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 0 /* Muzzle.Smile */]],
    ['>B)', [20 /* Eye.Angry2 */, 20 /* Eye.Angry2 */, 0 /* Muzzle.Smile */]],
    ['<B)', [16 /* Eye.Sad2 */, 16 /* Eye.Sad2 */, 0 /* Muzzle.Smile */]],
    ['|:)', [7 /* Eye.Frown */, 7 /* Eye.Frown */, 0 /* Muzzle.Smile */]],
    ['|B)', [8 /* Eye.Frown2 */, 8 /* Eye.Frown2 */, 0 /* Muzzle.Smile */]],
    ['|)', [11 /* Eye.Lines */, 11 /* Eye.Lines */, 0 /* Muzzle.Smile */]],
    [':))', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 18 /* Muzzle.SmileTeeth */]],
    [':]]', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 18 /* Muzzle.SmileTeeth */]],
    [':||', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 20 /* Muzzle.NeutralTeeth */]],
    [':((', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 19 /* Muzzle.FrownTeeth */]],
    [':[[', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 19 /* Muzzle.FrownTeeth */]],
    ['://', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 21 /* Muzzle.ConcernedTeeth */]],
    [':SS', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 21 /* Muzzle.ConcernedTeeth */]],
    [';)', [6 /* Eye.Closed */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    [';(', [16 /* Eye.Sad2 */, 16 /* Eye.Sad2 */, 1 /* Muzzle.Frown */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 8 /* ExpressionExtra.Tears */]],
    ['>;(', [19 /* Eye.Angry */, 19 /* Eye.Angry */, 1 /* Muzzle.Frown */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 8 /* ExpressionExtra.Tears */]],
    ['%)', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */, 0 /* Iris.Forward */, 1 /* Iris.Up */]],
    [`c':`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 8 /* ExpressionExtra.Tears */]],
    [`:')`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 8 /* ExpressionExtra.Tears */]],
    [`:'(`, [15 /* Eye.Sad */, 15 /* Eye.Sad */, 1 /* Muzzle.Frown */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 8 /* ExpressionExtra.Tears */]],
    [`=,)`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 8 /* ExpressionExtra.Tears */]],
    ['=`)', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 8 /* ExpressionExtra.Tears */]],
    // TODO: :@ :y :'9
    // horizontal (left)
    ['(-:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['|:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */]],
    ['(:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['[:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['c:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['C:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['rus с:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['rus С:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['):', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 1 /* Muzzle.Frown */]],
    ['D:', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 12 /* Muzzle.ConcernedOpen2 */]],
    ['DD:', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 16 /* Muzzle.ConcernedOpen3 */]],
    ['DDDDD:', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 16 /* Muzzle.ConcernedOpen3 */]],
    ['D:<', [19 /* Eye.Angry */, 19 /* Eye.Angry */, 12 /* Muzzle.ConcernedOpen2 */]],
    ['D8<', [19 /* Eye.Angry */, 19 /* Eye.Angry */, 12 /* Muzzle.ConcernedOpen2 */, 6 /* Iris.Shocked */, 6 /* Iris.Shocked */]],
    ['):<', [19 /* Eye.Angry */, 19 /* Eye.Angry */, 1 /* Muzzle.Frown */]],
    ['v:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 8 /* Muzzle.ConcernedOpen */]],
    ['/:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 7 /* Muzzle.Concerned */]],
    ['(:>', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 0 /* Muzzle.Smile */]],
    ['(:|', [7 /* Eye.Frown */, 7 /* Eye.Frown */, 0 /* Muzzle.Smile */]],
    ['(|', [11 /* Eye.Lines */, 11 /* Eye.Lines */, 0 /* Muzzle.Smile */]],
    ['((:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 18 /* Muzzle.SmileTeeth */]],
    ['[[:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 18 /* Muzzle.SmileTeeth */]],
    ['||:', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 20 /* Muzzle.NeutralTeeth */]],
    [')):', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 19 /* Muzzle.FrownTeeth */]],
    ['(;', [1 /* Eye.Neutral */, 6 /* Eye.Closed */, 0 /* Muzzle.Smile */]],
    // horizontal (invalid)
    ['||', undefined],
    ['|||', undefined],
    ['>||', undefined],
    ['>xD', undefined],
    ['(X<', undefined],
    ['x-x', undefined],
    // vertical
    ['-_-', [8 /* Eye.Frown2 */, 8 /* Eye.Frown2 */, 6 /* Muzzle.Flat */]],
    ['-.-', [8 /* Eye.Frown2 */, 8 /* Eye.Frown2 */, 13 /* Muzzle.Kiss */]],
    ['-,-', [8 /* Eye.Frown2 */, 8 /* Eye.Frown2 */, 13 /* Muzzle.Kiss */]],
    ['^_^', [13 /* Eye.ClosedHappy2 */, 13 /* Eye.ClosedHappy2 */, 6 /* Muzzle.Flat */]],
    ['-_^', [6 /* Eye.Closed */, 13 /* Eye.ClosedHappy2 */, 6 /* Muzzle.Flat */]],
    ['o_O', [2 /* Eye.Neutral2 */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */]],
    ['0_o', [1 /* Eye.Neutral */, 2 /* Eye.Neutral2 */, 6 /* Muzzle.Flat */]],
    ['o_o', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */]],
    ['o,o', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 13 /* Muzzle.Kiss */]],
    ['ono', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 1 /* Muzzle.Frown */]],
    ['O_O', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */, 6 /* Iris.Shocked */, 6 /* Iris.Shocked */]],
    ['OoO', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 8 /* Muzzle.ConcernedOpen */, 6 /* Iris.Shocked */, 6 /* Iris.Shocked */]],
    ['0_0', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */]],
    ['°_°', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */]],
    ['0.0', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 13 /* Muzzle.Kiss */]],
    ['._.', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */]],
    [',_,', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 6 /* Muzzle.Flat */]],
    ['v_V', [6 /* Eye.Closed */, 6 /* Eye.Closed */, 6 /* Muzzle.Flat */]],
    ['u_U', [6 /* Eye.Closed */, 6 /* Eye.Closed */, 6 /* Muzzle.Flat */]],
    ['n_n', [14 /* Eye.ClosedHappy */, 14 /* Eye.ClosedHappy */, 6 /* Muzzle.Flat */]],
    ['>_<', [23 /* Eye.X */, 23 /* Eye.X */, 6 /* Muzzle.Flat */, 2 /* Iris.Left */, 3 /* Iris.Right */]],
    ['>c<', [23 /* Eye.X */, 23 /* Eye.X */, 0 /* Muzzle.Smile */, 2 /* Iris.Left */, 3 /* Iris.Right */]],
    [`'c'`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['-C-', [6 /* Eye.Closed */, 6 /* Eye.Closed */, 0 /* Muzzle.Smile */]],
    ['rus -с-', [6 /* Eye.Closed */, 6 /* Eye.Closed */, 0 /* Muzzle.Smile */]],
    ['-v-', [6 /* Eye.Closed */, 6 /* Eye.Closed */, 0 /* Muzzle.Smile */]],
    ['-V-', [6 /* Eye.Closed */, 6 /* Eye.Closed */, 0 /* Muzzle.Smile */]],
    ['-U-', [6 /* Eye.Closed */, 6 /* Eye.Closed */, 0 /* Muzzle.Smile */]],
    ['-u-', [6 /* Eye.Closed */, 6 /* Eye.Closed */, 0 /* Muzzle.Smile */]],
    ['-w-', [6 /* Eye.Closed */, 6 /* Eye.Closed */, 0 /* Muzzle.Smile */]],
    ['-W-', [6 /* Eye.Closed */, 6 /* Eye.Closed */, 0 /* Muzzle.Smile */]],
    [`-👃-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 0 /* Muzzle.Smile */]],
    [`'_'`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */]],
    [`-*-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 13 /* Muzzle.Kiss */]],
    [`-x-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 13 /* Muzzle.Kiss */]],
    [`-X-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 13 /* Muzzle.Kiss */]],
    [`>x<`, [23 /* Eye.X */, 23 /* Eye.X */, 13 /* Muzzle.Kiss */, 2 /* Iris.Left */, 3 /* Iris.Right */]],
    [`-o-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 8 /* Muzzle.ConcernedOpen */]],
    [`-O-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 12 /* Muzzle.ConcernedOpen2 */]],
    [`-0-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 12 /* Muzzle.ConcernedOpen2 */]],
    [`^o^`, [13 /* Eye.ClosedHappy2 */, 13 /* Eye.ClosedHappy2 */, 9 /* Muzzle.SmileOpen2 */]],
    [`^O^`, [13 /* Eye.ClosedHappy2 */, 13 /* Eye.ClosedHappy2 */, 14 /* Muzzle.SmileOpen3 */]],
    [`-n-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 1 /* Muzzle.Frown */]],
    [`-m-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 1 /* Muzzle.Frown */]],
    [`-^-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 1 /* Muzzle.Frown */]],
    [`-~-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 7 /* Muzzle.Concerned */]],
    [`-3-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 13 /* Muzzle.Kiss */]],
    [`rus -з-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 13 /* Muzzle.Kiss */]],
    [`rus -э-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 13 /* Muzzle.Kiss */]],
    [`-q-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 23 /* Muzzle.NeutralPant */]],
    [`-p-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 23 /* Muzzle.NeutralPant */]],
    [`-P-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 22 /* Muzzle.SmilePant */]],
    [`-Q-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 22 /* Muzzle.SmilePant */]],
    [`-A-`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 12 /* Muzzle.ConcernedOpen2 */]],
    [`q-q`, [15 /* Eye.Sad */, 15 /* Eye.Sad */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`p-p`, [15 /* Eye.Sad */, 15 /* Eye.Sad */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`p-q`, [15 /* Eye.Sad */, 15 /* Eye.Sad */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`rus р-р`, [15 /* Eye.Sad */, 15 /* Eye.Sad */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`;-;`, [15 /* Eye.Sad */, 15 /* Eye.Sad */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`:-:`, [15 /* Eye.Sad */, 15 /* Eye.Sad */, 2 /* Muzzle.Neutral */]],
    [`P-P`, [15 /* Eye.Sad */, 15 /* Eye.Sad */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`rus Р-Р`, [15 /* Eye.Sad */, 15 /* Eye.Sad */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`t-t`, [21 /* Eye.Peaceful */, 21 /* Eye.Peaceful */, 2 /* Muzzle.Neutral */]],
    [`Т_Т`, [21 /* Eye.Peaceful */, 21 /* Eye.Peaceful */, 6 /* Muzzle.Flat */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`rus Т_т`, [21 /* Eye.Peaceful */, 21 /* Eye.Peaceful */, 6 /* Muzzle.Flat */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`Q-Q`, [15 /* Eye.Sad */, 15 /* Eye.Sad */, 2 /* Muzzle.Neutral */, 6 /* Iris.Shocked */, 6 /* Iris.Shocked */, 4 /* ExpressionExtra.Cry */]],
    [`y-y`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`Y-Y`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`у-у`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`У-У`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 4 /* ExpressionExtra.Cry */]],
    [`ò_ó`, [19 /* Eye.Angry */, 19 /* Eye.Angry */, 6 /* Muzzle.Flat */]],
    [`ó_ò`, [15 /* Eye.Sad */, 15 /* Eye.Sad */, 6 /* Muzzle.Flat */]],
    [`ô_ô`, [7 /* Eye.Frown */, 7 /* Eye.Frown */, 6 /* Muzzle.Flat */]],
    [`õ_õ`, [7 /* Eye.Frown */, 7 /* Eye.Frown */, 6 /* Muzzle.Flat */]],
    [`ō_ō`, [7 /* Eye.Frown */, 7 /* Eye.Frown */, 6 /* Muzzle.Flat */]],
    [`ŏ_ŏ`, [7 /* Eye.Frown */, 7 /* Eye.Frown */, 6 /* Muzzle.Flat */]],
    [`Ò_Ó`, [19 /* Eye.Angry */, 19 /* Eye.Angry */, 6 /* Muzzle.Flat */, 6 /* Iris.Shocked */, 6 /* Iris.Shocked */]],
    [`Ô_Ô`, [7 /* Eye.Frown */, 7 /* Eye.Frown */, 6 /* Muzzle.Flat */, 6 /* Iris.Shocked */, 6 /* Iris.Shocked */]],
    [`Õ_Õ`, [7 /* Eye.Frown */, 7 /* Eye.Frown */, 6 /* Muzzle.Flat */, 6 /* Iris.Shocked */, 6 /* Iris.Shocked */]],
    [`Ō_Ō`, [7 /* Eye.Frown */, 7 /* Eye.Frown */, 6 /* Muzzle.Flat */, 6 /* Iris.Shocked */, 6 /* Iris.Shocked */]],
    [`Ŏ_Ŏ`, [7 /* Eye.Frown */, 7 /* Eye.Frown */, 6 /* Muzzle.Flat */, 6 /* Iris.Shocked */, 6 /* Iris.Shocked */]],
    [`=_=`, [4 /* Eye.Neutral4 */, 4 /* Eye.Neutral4 */, 6 /* Muzzle.Flat */]],
    [`a_a`, [8 /* Eye.Frown2 */, 8 /* Eye.Frown2 */, 6 /* Muzzle.Flat */]],
    [`e_e`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */, 4 /* Iris.UpLeft */, 4 /* Iris.UpLeft */]],
    [`е_е`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */, 4 /* Iris.UpLeft */, 4 /* Iris.UpLeft */]],
    [`g_g`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */, 5 /* Iris.UpRight */, 5 /* Iris.UpRight */]],
    [`9_9`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */, 1 /* Iris.Up */, 1 /* Iris.Up */]],
    [`6_9`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */, 0 /* Iris.Forward */, 1 /* Iris.Up */]],
    ['>_>', [2 /* Eye.Neutral2 */, 2 /* Eye.Neutral2 */, 6 /* Muzzle.Flat */, 2 /* Iris.Left */, 2 /* Iris.Left */]],
    ['<_<', [2 /* Eye.Neutral2 */, 2 /* Eye.Neutral2 */, 6 /* Muzzle.Flat */, 3 /* Iris.Right */, 3 /* Iris.Right */]],
    ['<_>', [2 /* Eye.Neutral2 */, 2 /* Eye.Neutral2 */, 6 /* Muzzle.Flat */, 3 /* Iris.Right */, 2 /* Iris.Left */]],
    ['d_d', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */, 3 /* Iris.Right */, 3 /* Iris.Right */]],
    ['b_b', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */, 2 /* Iris.Left */, 2 /* Iris.Left */]],
    ['twO', [21 /* Eye.Peaceful */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['o//o', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 1 /* ExpressionExtra.Blush */]],
    ['o/////o', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 1 /* ExpressionExtra.Blush */]],
    ['o\\\\o', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 1 /* ExpressionExtra.Blush */]],
    ['o\\\\\\o', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 2 /* Muzzle.Neutral */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 1 /* ExpressionExtra.Blush */]],
    ['>//<', [23 /* Eye.X */, 23 /* Eye.X */, 2 /* Muzzle.Neutral */, 2 /* Iris.Left */, 3 /* Iris.Right */, 1 /* ExpressionExtra.Blush */]],
    ['-//v//-', [6 /* Eye.Closed */, 6 /* Eye.Closed */, 0 /* Muzzle.Smile */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 1 /* ExpressionExtra.Blush */]],
    ['-///v///-', [6 /* Eye.Closed */, 6 /* Eye.Closed */, 0 /* Muzzle.Smile */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 1 /* ExpressionExtra.Blush */]],
    [';//v//;', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 0 /* Muzzle.Smile */, 0 /* Iris.Forward */, 0 /* Iris.Forward */, 1 /* ExpressionExtra.Blush */ | 4 /* ExpressionExtra.Cry */]],
    [`6_6`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */, 7 /* Iris.Down */, 7 /* Iris.Down */]],
    ['6.6', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 13 /* Muzzle.Kiss */, 7 /* Iris.Down */, 7 /* Iris.Down */]],
    ['bcd', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */, 7 /* Iris.Down */, 7 /* Iris.Down */]],
    // TODO: o-o' o-o' ~_~ @_@ o=o oyo *_* (amazed) -_-/ -_-\ D_D
    // vertical (short)
    ['^^', [13 /* Eye.ClosedHappy2 */, 13 /* Eye.ClosedHappy2 */, 0 /* Muzzle.Smile */]],
    ['))', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['((', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 1 /* Muzzle.Frown */]],
    ['<<', [2 /* Eye.Neutral2 */, 2 /* Eye.Neutral2 */, 6 /* Muzzle.Flat */, 3 /* Iris.Right */, 3 /* Iris.Right */]],
    ['>>', [2 /* Eye.Neutral2 */, 2 /* Eye.Neutral2 */, 6 /* Muzzle.Flat */, 2 /* Iris.Left */, 2 /* Iris.Left */]],
    // vertical (invalid)
    ...[
        '---', '...', '000', 'QQQ', 'One', 'Up.', 'UP.',
        ...expressionUtils_1.THREE_LETTER_WORDS,
        ...expressionUtils_1.THREE_LETTER_WORDS.map(x => x.toUpperCase()),
        ...expressionUtils_1.TWO_LETTER_WORDS.map(x => x + '.'),
        ...expressionUtils_1.TWO_LETTER_WORDS.map(x => x + ','),
        ...expressionUtils_1.TWO_LETTER_WORDS.map(x => x + '-'),
        ...expressionUtils_1.TWO_LETTER_WORDS.map(x => x + '*'),
    ].map(x => [x, undefined]),
    ['BS', undefined],
    ['x8', undefined],
    ['8x', undefined],
    ['xx', undefined],
    ['-//c-', undefined],
    ['-c//-', undefined],
    ['030', undefined],
    ['80', undefined],
    // other
    [`aaaaa`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 16 /* Muzzle.ConcernedOpen3 */]],
    [`AAAAAA`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 16 /* Muzzle.ConcernedOpen3 */, 6 /* Iris.Shocked */, 6 /* Iris.Shocked */]],
    [`aaaaa...`, [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 16 /* Muzzle.ConcernedOpen3 */]],
    [`zzz`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 2 /* Muzzle.Neutral */]],
    [`ZZZZZ`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 2 /* Muzzle.Neutral */]],
    [`zzz...`, [6 /* Eye.Closed */, 6 /* Eye.Closed */, 2 /* Muzzle.Neutral */]],
    // emoji
    ['🙂', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */]],
    ['😵', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 0 /* Muzzle.Smile */, 1 /* Iris.Up */, 0 /* Iris.Forward */]],
    ['😐', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 6 /* Muzzle.Flat */]],
    ['😑', [11 /* Eye.Lines */, 11 /* Eye.Lines */, 6 /* Muzzle.Flat */]],
    ['😆', [23 /* Eye.X */, 23 /* Eye.X */, 5 /* Muzzle.SmileOpen */]],
    ['😟', [15 /* Eye.Sad */, 15 /* Eye.Sad */, 2 /* Muzzle.Neutral */]],
    ['😠', [19 /* Eye.Angry */, 19 /* Eye.Angry */, 0 /* Muzzle.Smile */]],
    ['🤔', [1 /* Eye.Neutral */, 8 /* Eye.Frown2 */, 13 /* Muzzle.Kiss */]],
    ['😈', [19 /* Eye.Angry */, 19 /* Eye.Angry */, 0 /* Muzzle.Smile */, 1 /* Iris.Up */, 0 /* Iris.Forward */]],
    ['👿', [19 /* Eye.Angry */, 19 /* Eye.Angry */, 18 /* Muzzle.SmileTeeth */]],
    // unsafe faces
    [':L', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 23 /* Muzzle.NeutralPant */]],
    [':Q', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 22 /* Muzzle.SmilePant */]],
    // safe replacements
    [':u', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 11 /* Muzzle.NeutralOpen2 */]],
    [':DD', [1 /* Eye.Neutral */, 1 /* Eye.Neutral */, 9 /* Muzzle.SmileOpen2 */]],
];
//# sourceMappingURL=expressions.js.map