"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("../lib");
const chai_1 = require("chai");
const animator_1 = require("../../common/animator");
const sit = { name: 'sit', fps: 6, loop: true, frames: { length: 12 } };
const sit2 = { name: 'sit2', fps: 6, loop: true, frames: { length: 12 } };
const stand = { name: 'stand', fps: 6, loop: true, frames: { length: 6 } };
const run = { name: 'run', fps: 6, loop: true, frames: { length: 6 } };
describe('Animator', () => {
    let animator;
    beforeEach(() => {
        animator = (0, animator_1.createAnimator)();
    });
    after(() => {
        animator = undefined;
    });
    it('returns undefined animation by default', () => {
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).undefined;
    });
    it('returns 0 frame by default', () => {
        (0, chai_1.expect)((0, animator_1.getAnimationFrame)(animator)).equal(0);
    });
    it('sets initial state', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, chai_1.expect)(animator.state).equal(sitting);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(sit);
    });
    it('does not switch to new state immediately', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, running);
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(sit);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(sit);
    });
    it('updates animation frame', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, animator_1.updateAnimator)(animator, 1);
        (0, chai_1.expect)((0, animator_1.getAnimationFrame)(animator)).equal(6);
    });
    it('loops animation frame', () => {
        const state = (0, animator_1.animatorState)('sitting', sit);
        (0, animator_1.setAnimatorState)(animator, state);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)((0, animator_1.getAnimationFrame)(animator)).equal(6);
    });
    it('switches to next state immediately if exitAfter is set to 0', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, running, { exitAfter: 0 });
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(run);
    });
    it('switches to next state after half of the animation if exitAfter is set 0.5', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, running, { exitAfter: 0.5 });
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(sit, 'after 0.1s');
        (0, animator_1.updateAnimator)(animator, 0.4);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(sit, 'after 0.5s');
        (0, animator_1.updateAnimator)(animator, 0.6);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(run, 'after 1.1s');
    });
    it('switches to next state immediately if exitAfter is set 0.5 and time is already past 0.5', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, running, { exitAfter: 0.5 });
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, animator_1.updateAnimator)(animator, 1.1);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(run);
    });
    it('switches to middle of next state if enterTime is set to 0.5', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, running, { exitAfter: 0, enterTime: 0.5 });
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(run);
        (0, chai_1.expect)((0, animator_1.getAnimationFrame)(animator)).equal(3);
    });
    it('keeps time of animation after switching if keepTime is set', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, running, { exitAfter: 0, keepTime: true });
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, animator_1.updateAnimator)(animator, 0.5);
        (0, chai_1.expect)((0, animator_1.getAnimationFrame)(animator)).equal(3, 'before');
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(run);
        (0, chai_1.expect)((0, animator_1.getAnimationFrame)(animator)).equal(3, 'after');
    });
    it('switches to state if set to switch from any', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, running, { exitAfter: 0 });
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(run);
    });
    it('does not use switch from any state as intermediate transition', () => {
        const lying = (0, animator_1.animatorState)('lying', sit);
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const standing = (0, animator_1.animatorState)('standing', sit);
        const flying = (0, animator_1.animatorState)('flying', sit);
        const hovering = (0, animator_1.animatorState)('hovering', sit);
        (0, animator_1.animatorTransition)(lying, sitting);
        (0, animator_1.animatorTransition)(sitting, standing);
        (0, animator_1.animatorTransition)(animator_1.anyState, flying);
        (0, animator_1.animatorTransition)(flying, hovering);
        (0, animator_1.animatorTransition)(standing, hovering);
        (0, animator_1.setAnimatorState)(animator, lying);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, animator_1.setAnimatorState)(animator, hovering);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)(animator.state).equal(sitting);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)(animator.state).equal(standing);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)(animator.state).equal(hovering);
    });
    it('does not use switch from any state is another transition is possible', () => {
        const lying = (0, animator_1.animatorState)('lying', sit);
        const standing = (0, animator_1.animatorState)('standing', sit);
        const hovering = (0, animator_1.animatorState)('hovering', sit);
        (0, animator_1.animatorTransition)(lying, standing);
        (0, animator_1.animatorTransition)(animator_1.anyState, hovering);
        (0, animator_1.animatorTransition)(standing, hovering);
        (0, animator_1.setAnimatorState)(animator, lying);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, animator_1.setAnimatorState)(animator, hovering);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)(animator.state).equal(standing);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)(animator.state).equal(hovering);
    });
    it('uses switch from any state is another transition is possible but longer than 2 jumps', () => {
        const lying = (0, animator_1.animatorState)('lying', sit);
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const standing = (0, animator_1.animatorState)('standing', sit);
        const hovering = (0, animator_1.animatorState)('hovering', sit);
        (0, animator_1.animatorTransition)(lying, sitting);
        (0, animator_1.animatorTransition)(sitting, standing);
        (0, animator_1.animatorTransition)(animator_1.anyState, hovering);
        (0, animator_1.animatorTransition)(standing, hovering);
        (0, animator_1.setAnimatorState)(animator, lying);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, animator_1.setAnimatorState)(animator, hovering);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)(animator.state).equal(hovering);
    });
    it('does not switch to next state immediately if exitNow is not set', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, running);
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(sit);
    });
    it('switches to next state when animation is finished', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, running);
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(run);
        (0, chai_1.expect)((0, animator_1.getAnimationFrame)(animator)).equal(0);
    });
    it('does nothing if switching to already targeted state', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, running);
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(run);
    });
    it('does nothing if transition is no possible', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(sit);
    });
    it('switches through intermediate state', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const other = (0, animator_1.animatorState)('other', sit);
        const standing = (0, animator_1.animatorState)('standing', stand);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, standing);
        (0, animator_1.animatorTransition)(other, running);
        (0, animator_1.animatorTransition)(standing, running);
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(stand);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(run);
    });
    it('switches directly to target state if exitNow is set on both states', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const standing = (0, animator_1.animatorState)('standing', stand);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, standing, { exitAfter: 0 });
        (0, animator_1.animatorTransition)(standing, running, { exitAfter: 0 });
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(run);
    });
    it('cancells switch to target state', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, running);
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 3);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(sit);
    });
    it('handles loops in states', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit);
        const standing0 = (0, animator_1.animatorState)('standing0', sit);
        const standing1 = (0, animator_1.animatorState)('standing1', stand);
        const standing2 = (0, animator_1.animatorState)('standing2', stand);
        const running = (0, animator_1.animatorState)('running', run);
        (0, animator_1.animatorTransition)(sitting, standing0, { exitAfter: 0 });
        (0, animator_1.animatorTransition)(running, standing1, { exitAfter: 0 });
        (0, animator_1.animatorTransition)(running, standing2, { exitAfter: 0 });
        (0, animator_1.animatorTransition)(standing0, standing2, { exitAfter: 0 });
        (0, animator_1.animatorTransition)(standing1, running, { exitAfter: 0 });
        (0, animator_1.animatorTransition)(standing2, running, { exitAfter: 0 });
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, animator_1.setAnimatorState)(animator, running);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(run);
    });
    it('returns correct animation variant', () => {
        const sitting = (0, animator_1.animatorState)('sitting', sit, { alt: sit2 });
        animator.variant = 'alt';
        (0, animator_1.setAnimatorState)(animator, sitting);
        (0, animator_1.updateAnimator)(animator, 0.1);
        (0, chai_1.expect)((0, animator_1.getAnimation)(animator)).equal(sit2);
    });
    it('does not use shorter transition route if onlyDirectTo is set', () => {
        const standing = (0, animator_1.animatorState)('standing', run);
        const standingUp = (0, animator_1.animatorState)('standing-up', run);
        const sitting = (0, animator_1.animatorState)('sitting', run);
        const sittingUp = (0, animator_1.animatorState)('sitting-up', run);
        const lying = (0, animator_1.animatorState)('lying', run);
        const lyingToTrotting = (0, animator_1.animatorState)('lying-to-trotting', run);
        const trotting = (0, animator_1.animatorState)('trotting', run);
        (0, animator_1.animatorTransition)(lying, sittingUp);
        (0, animator_1.animatorTransition)(sittingUp, sitting);
        (0, animator_1.animatorTransition)(sitting, standingUp);
        (0, animator_1.animatorTransition)(standingUp, standing);
        (0, animator_1.animatorTransition)(lying, lyingToTrotting, { onlyDirectTo: trotting });
        (0, animator_1.animatorTransition)(lyingToTrotting, standing);
        (0, animator_1.animatorTransition)(lyingToTrotting, trotting);
        (0, animator_1.setAnimatorState)(animator, lying);
        (0, animator_1.updateAnimator)(animator, 0);
        (0, animator_1.setAnimatorState)(animator, standing);
        (0, animator_1.updateAnimator)(animator, 1.1);
        (0, chai_1.expect)(animator.state).equal(sittingUp);
        (0, animator_1.updateAnimator)(animator, 1.1);
        (0, chai_1.expect)(animator.state).equal(sitting);
        (0, animator_1.updateAnimator)(animator, 1.1);
        (0, chai_1.expect)(animator.state).equal(standingUp);
        (0, animator_1.updateAnimator)(animator, 1.1);
        (0, chai_1.expect)(animator.state).equal(standing);
    });
});
//# sourceMappingURL=animator.spec.js.map